<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Language_ng-untouched ng-pristine ng-_b7e998</name>
   <tag></tag>
   <elementGuidId>c1b6e030-e45a-40cf-a7b3-b719b14f2bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-untouched.ng-pristine.ng-invalid.input-full-width.size-large.status-basic.shape-rectangle.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>505c1d80-aa8a-4123-b6cb-6fef9cd78581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldsize</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>85f28c73-fb47-4a25-8893-e270b8a9bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>12b19dc6-2fa0-4fd5-8494-6dddd5e6cbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1dc1332b-63fe-48b7-af98-b16ac83d847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>508eb89f-90c7-4a79-b7f6-f436df121c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid input-full-width size-large status-basic shape-rectangle nb-transition</value>
      <webElementGuid>b7ea8ca8-fb54-4295-a32a-80076bc6f9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default pace-done pace-done&quot;]/ngx-app[1]/identity[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-login[1]/div[@class=&quot;container-out&quot;]/div[@class=&quot;container-login&quot;]/div[@class=&quot;form-left&quot;]/div[3]/form[@class=&quot;form w-100 ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;form-group&quot;]/nb-form-field[@class=&quot;nb-form-field-size-large nb-transition&quot;]/div[@class=&quot;nb-form-control-container nb-form-field-control-with-prefix nb-form-field-control-with-suffix&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-invalid input-full-width size-large status-basic shape-rectangle nb-transition&quot;]</value>
      <webElementGuid>940cc558-ffe3-4276-9b2f-6b3121b5c31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>d924f759-0b70-4975-b54b-1122186d2f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nb-form-field/div[2]/input</value>
      <webElementGuid>8afa4d97-862c-4b2c-a086-c449597003a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>d49891dd-1930-4ed5-9d3c-7139187893d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
