<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_VNHCM</name>
   <tag></tag>
   <elementGuidId>93ee25d3-2082-4002-b5de-2f246a5070a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a07087ff8c4f-1 > tr.data-row.row-data-search > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a07087ff8c4f-1']/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;VNHCM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>678693e1-681a-4d8a-afee-cc55fdfb01cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b641b27-c2c7-4d25-892f-7d2e189cb653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VNHCM</value>
      <webElementGuid>8892c2e6-49b4-48a6-812b-666f4c7c5e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a07087ff8c4f-1&quot;)/tr[@class=&quot;data-row row-data-search&quot;]/td[1]</value>
      <webElementGuid>2553b2a0-8210-4d1a-9280-24fb47bc5c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a07087ff8c4f-1']/tr/td</value>
      <webElementGuid>8813467b-3950-48ba-9ea9-ae0c8c31e58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOWATCO - HAN'])[2]/following::td[1]</value>
      <webElementGuid>7adcaa4a-ca48-4b63-82b0-6542fc16381a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công ty CP Đường Sông Miền Nam - HAN'])[1]/following::td[2]</value>
      <webElementGuid>eb4be67d-4def-43aa-a88a-f7eaf017160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công ty CP Đường Sông Miền Nam - HCM'])[1]/preceding::td[1]</value>
      <webElementGuid>69b1dc3d-f341-40c1-8c25-8aec1fb7ebee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOWATCO - HCM'])[1]/preceding::td[2]</value>
      <webElementGuid>179fd980-dbdf-42b1-b466-7bf156d583e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VNHCM']/parent::*</value>
      <webElementGuid>3061b8f1-3f3c-4b0f-9de9-c93ba4f9f935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/tr/td</value>
      <webElementGuid>5597c880-6253-433f-b60c-fb4350e92fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'VNHCM' or . = 'VNHCM')]</value>
      <webElementGuid>56da27fa-2ba7-4ff3-a277-5c44b76be96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ade71869ccc6-1']/tr/td</value>
      <webElementGuid>77d2f5d5-ac31-470c-8348-eea6f9729242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
